name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/jiviteshoo7/myportfolio/blob/main/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/jiviteshoo7/myportfolio"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "Jivitesh Varshney"
  homepage = "https://www.linkedin.com/in/jivitesh-varshney-848641154/"
